### ISSUE TITLE
Morphology extraction for multi-component models

### ISSUE THREAD

**Issue by pmelchior** [SampsonML/equinox_score_model#1]
The network trains on morphology images from scarlet1. But scarlet1 uses 2 components for every galaxy with sufficient SNR. This begs the question how we deal with these two morphology images per source. Two options come to mind:

1. Combine the 2 components into one with a SED-weighted sum across all bands (=channels $c$): $im = \sum_c SED_c^{(1)} morph^{(1)} + SED_c^{(2)} morph^{(2)}$
2. Render the 2-component model in every band $im_c = SED_c^{(1)} morph^{(1)} + SED_c^{(2)} morph^{(2)}$ and use them separately for training.

The first option is the simplest and accurate if there are only small SED variations between the components. Otherwise we'll assume a weighted average that doesn't actually exist in nature.

The second option is overkill if there are only small SED variations between the components. However, it allows for training that acknowledges different morphological mixtures between the components, namely implicitly from the how these combinations would look in different bands.

As long as we're using a single-component network for all morphologies, neither of them is entirely appropriate. But I think that option 2 reduces the consequences of this mismatch. So, let's work with it. However, if we simply stored 5 different images for every multi-component source, we change the balance of single-component to multi-component sources in the training data. To avoid that let's **randomly select a single band for every source**. This will work for single- and multi-component source and not change the balance between them.

**Comment by SampsonML** [comment]
Ok so essentially for each image, we go
`if multi_band: idx = random.choice([0-5])`
then 
`model = blend.components[component_idx]
  for i in len(model): gal_source = model.morph[idx]
                                  # save the source`
  
  So I have two questions.
  1, the eqn implies I need to multiply the morph array by some SED weighting, but is using option two there is no need for this?
  2, Currently say for a scene with 5 sources, I store each source as an assumed isolated galaxy. Is this no longer what I should do?
  
 Potentially I am misunderstanding the code a bit , and the blend components ARE the different bands.

**Comment by pmelchior** [comment]
You're mixing up components and bands, I think. I'm not quite sure how the LSST wrapper for scarlet works, but this is almost certainly incorrect: `gal_source = model.morph[idx]` because this is the morphology image for a single component.
What you want is to combine the morphology images of multiple components. So, something like

```
im = np.zeros(H,W)
c = np.random.choice(C)
for k in range(len(components)):
    im += SED[k, c] * morph[k]
```
